baseURL = "https://audiovideomerger.github.io/"
languageCode = "en-us"
title = "Audio Video Merger"
disableKinds = ["taxonomy"]
[params]
    author = "Kasper Koman"
    description = "Audio Video Merger is a one-trick-pony for painlessly replacing audio under video files."
