name: Build

on:
  workflow_call:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, arm64]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build and package app zip
        run: make zip-${{ matrix.arch }}

      - name: Upload app zip
        uses: actions/upload-artifact@v7
        with:
          name: zip-${{ matrix.arch }}
          path: dist/AudioVideoMerger-darwin-${{ matrix.arch }}-*.zip
          if-no-files-found: error
          compression-level: 0
